data:
    name: 'coco'
    resize: [320,240]
    image_train_path: ['./data/mp_coco/images/train',]
    label_train_path: ['./data/mp_coco/labels/train/',]
    image_test_path: './data/mp_coco/images/test/'
    label_test_path: './data/mp_coco/labels/test/'
    augmentation:
        photometric:
            enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.3, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: true
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                patch_ratio: 0.85
                max_angle: 1.57
                allow_artifacts: true
            valid_border_margin: 3
model:
    name: 'magicpoint'
    grid_size: 8
    det_thresh: 0.001 # 1/65
    nms: 4
    topk: -1
    pretrained_model: 'none'
    backbone:
        backbone_type: 'VGG' #ResNetFPN
        vgg:
            channels: [64,64,64,64,128,128,128,128]
    det_head: #detector head
        feat_in_dim: 128
    des_head: #descriptor head,ignore
        feat_in_dim: 128
        feat_out_dim: 256
solver:
    epoch: 2
    base_lr: 0.01
    train_batch_size: 16
    test_batch_size: 16
    save_dir: './export'
    model_name: 'mg_coco'
    detection_threshold: 0.015 #0.015
    nms: 4
    grid_size: 8

